config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => "posts#home"
  resources :posts do
    post 'check'
    resources :comments
  end
  resources :categories
  get '/:url_short' => 'posts#redirect'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :category_type

  has_many :posts
  # belongs_to :user
end

app/models/city.rb
class City < ApplicationRecord
  validates_presence_of :code
  validates_presence_of :name
  belongs_to :region
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :content

  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :address
  validates_presence_of :generate_short_url

  belongs_to :user
  belongs_to :category
  has_many :comments

  mount_uploader :image, ImageUploader

  def generate_short_url
    loop do
      @surl = rand(1..9998).to_s.rjust(4,'0')
      break unless Post.exists?(url_short: @surl)
    end
    self.url_short = @surl
  end
end

app/models/region.rb
class Region < ApplicationRecord
  validates_presence_of :code
  validates_presence_of :name
  validates_presence_of :region_name
  has_many :cities
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable  and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :posts
  has_many :comments
  # has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  def index
    @disaster = Category.all
  end

  def new
    @disaster = Category.new
  end

  def create
    @param = params.require(:category).permit(:category_type)
    @disaster = Category.new(@param)
    if @disaster.save
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @disaster = Category.find(params[:id])
  end

  def update
    @param = params.require(:category).permit(:category_type)
    @disaster = Category.find(params[:id])
    if @disaster.update(@param)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def show
    @disaster = Category.find(params[:id])
  end


  def destroy
    if @comment.destroy
      redirect_to categories_path(@post)
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post
  before_action :set_comment,:set_own_comment, only: [:edit, :update, :destroy]

  def index
    @comments = @post.comments
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user
    if @comment.save
      redirect_to post_comments_path(@post)
    else
      render :new
    end
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      redirect_to post_comments_path(@post, @comment)
    else
      render :edit
    end
  end

  def destroy
    if @comment.destroy
      redirect_to post_comments_path(@post)
    end
  end

  private

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

  def set_post
    @post = Post.find params[:post_id]
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_own_comment
    @comment = current_user.comments.find_by_id(params[:id])
    if @comment.nil?
      flash[:alert] = 'this comment is not belongs to you or not exists'
      redirect_to post_comments_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: :home
  before_action :set_post, only: :show
  before_action :set_own_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.includes(:user)
    @domain = request.base_url
    @posts = Post.all.includes(:user, :category).left_joins(:comments).group(:id).order("count(comments.id) desc")
  end

  def home
    @posts = Post.includes(:user)
    @posts = Post.all.includes(:user, :category).page(params[:page]).per(4)
  end

  def new
    @post = Post.new
  end

  def redirect
    @maigsing_url = params[:url_short]
    @post = Post.find_by(url_short: @maigsing_url)
    redirect_to post_path(@post)
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def show; end

  def destroy
    if @post.comments.size == 0
      @post.destroy
      redirect_to posts_path
    end
  end

  private

  def set_own_post
    @post = current_user.posts.find_by_id(params[:id])
    if @post.nil?
      flash[:alert] = 'this post not belongs to you or not exists'
      redirect_to posts_path
    end
  end

  def post_params
    params.require(:post).permit(:title, :content, :address, :category_id, :image)
  end

  def set_post
    @post = Post.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/edit.html.erb
<%= form_for @disaster, url:category_path(@disaster) , method: :patch do |f| %>
  <% if @disaster.errors.any? %>
    <% @disaster.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :category_type %>
    <%= f.text_field :category_type, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/index.html.erb
<h1>Hello, World!</h1>
<% @disaster.each do |category|%>
  <div><%=category.category_type%></div>
  <div><%=category.id%></div>
  <%= link_to 'edit', edit_category_path(category)  %>
  <%= link_to "show", category_path(category) %>

<!--  <button>-->
    <%#= form_for category, url: categories_path(category), method: :delete do |f| %>
      <%#= f.submit "delete" if category.user == current_user %>
    <%# end %>
<!--  </button>-->
<% end %>



<%= link_to "new", new_category_path %>

app/views/categories/new.html.erb
<%= form_for @disaster, url: categories_path, method: :post do |f| %>
  <% if @disaster.errors.any? %>
    <% @disaster.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>
  <div class="form-group">
    <%= f.label :category_type %>
    <%= f.text_field :category_type, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/categories/show.html.erb
<%=@disaster.category_type %>
<br>
<%=@disaster.post.content %>

app/views/comments/_form.html.erb
<% if comment.errors.any? %>
  <% comment.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<div class="form-group">
  <%= f.label :comment %>
  <%= f.text_field :comment, class: 'form-control' %>
</div>

<div class="form-group">
  <%= f.submit class: 'btn btn-primary' %>
</div>

app/views/comments/edit.html.erb
<%= link_to 'index', posts_path %>
<h1>Edit Post id: <%= @post.id %>, Comment ID:<%= @comment.id %></h1>

<%= form_for @comment, url: post_comment_path(@post, @comment), method: :patch do |f| %>
  <p><%= f.label :content %></p>
  <p><%= f.text_area :content %></p>
  <%= f.submit %>
<% end %>

app/views/comments/index.html.erb
<%= link_to 'index', posts_path %>
<% @comments.each do |comment| %>
  <label><p>Content : <%= comment.content %></p></label>

  <p><%= link_to 'edit', edit_post_comment_path(@post, comment) %></p>
  <p><%= button_to "delete", post_comment_path(@post, comment), method: :delete, data: { confirm: "Are you sure?" } %>
<% end %>
</p>

<%= link_to 'new', new_post_comment_path(@post) %>

app/views/comments/new.html.erb
<%= link_to 'index', posts_path %>
<h2>New comment for Post id<%= @post.id %></h2>
<%= form_for @comment, url: post_comments_path(@post), method: :post do |f| %>
  <p><%= f.label :content %></p>
  <p><%= f.text_area :content %></p>

  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<% if post.errors.any? %>
  <% post.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
<% end %>
<div class="container">
  <div>
    <div>
      <%= f.label :category %>
      <%= f.collection_select :category_id, Category.order(:category_type),:id,:category_type, include_blank: true %>
    </div>
  </div>
  <div>
    <div>
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.label :content %>
      <%= f.text_field :content, class: 'form-control' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.label :image %>
      <%= f.file_field :image, class: 'form-control' %>
    </div>
  </div>
  <div>
    <div>
      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>
    </div>
  </div>

  <div>
    <div>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post Id: <%= @post.id %></h1>

<%= form_for @post, url: post_path(@post), method: :patch do |f| %>
  <%= render partial: 'form', locals: {f: f, post: @post} %>
<% end %>
<%= link_to 'index', posts_path %>

app/views/posts/home.html.erb
<h1>Disaster Information Table</h1>
<button><%= link_to 'login', new_user_session_path %></button>
<button><%= link_to 'register', new_user_registration_path %></button>

<% @posts.each do |post| %>

  <div>
    <p><%= image_tag "http://localhost:3000/#{post.image.url}" if post.image? %></p>
  </div>

  <div>
    <b>email:</b>
    <p><%= post.user.email %></p>
  </div>
  <div>
    <b>title:</b>
    <p><%= post.title %></p>
  </div>

  <div>
    <b>content:</b>
    <p><%= post.content %></p>
  </div>

  <div>
    <b>address:</b>
    <p><%= post.address %></p>
  </div>

  <div>
    <p><b><%= Post.human_attribute_name(:comments) %> : </b><%= post.comments.count %></p>
  </div>
<% end %>
<%= paginate @posts %>

app/views/posts/index.html.erb
<p style="text-align: right"><%= link_to "LOGOUT", destroy_user_session_path, :method => :delete %></p>

<h1>Disaster Information Blog</h1>
<table>
  <thead>
  <tr>
    <th scope="col">Image</th>
    <th scope="col">Email</th>
    <th scope="col">Disaster</th>
    <th scope="col">Title</th>
    <th scope="col">Short URL</th>
    <th scope="col">Address</th>
    <th scope="col">Content</th>
    <th scope="col">Comments</th>
    <th scope="col">Action</th>
  </tr>
  </thead>

  <tbody>
  <% @posts.each do |post| %>
    <tr>
      <td><%= image_tag "http://localhost:3000/#{post.image.url}" if post.image? %></td>
      <td><%= post.user.email %></td>
      <td><%= post.category.category_type %></td>
      <td><%= post.title %></td>
      <td><%= link_to "#{@domain}/#{post.url_short}", post.url_short %></td>
      <td><%= post.address %></td>
      <td><%= post.content %></td>
      <td><%= post.comments.count %></td>
      <td>
        <button type="button" class="btn btn-info"><%= link_to :comments, post_comments_path(post) %></button>
        <button type="button" class="btn btn-info"><%= link_to "show ", post_path(post) %></button>
        <%= link_to "edit ", edit_post_path(post) if post.user == current_user %>
        <%= form_for post, url: post_path(post), method: :delete do |f| %>
          <%= f.submit "delete" if post.user == current_user %>
        <% end %>
      </td>
    </tr>
  <% end %>

  <%= link_to 'New', new_post_path, class: 'btn btn-success mb-4' %>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post, url: posts_path, method: :post do |f| %>
  <%= render partial: 'form', locals: {f: f, post: @post} %>
<% end %>

app/views/posts/show.html.erb
<h1>show post id <%= @post.id %></h1>
<div>
  <p><b>Title :</b> <%= @post.title %></p>
  <p><b>Content :</b> <%= @post.content %></p>
  <p><b>Address :</b> <%= @post.address %></p>
</div>

<%= link_to 'index', posts_path %>
<%= link_to 'edit', edit_post_path(@post)  %>